# Travis Build file for tsfresh
language: python
os: linux
# We want the pip folder to be cached, to speed up installation
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade pip wheel setuptools
  - pip install -r requirements.txt -r test-requirements.txt
  - pip install -U .
  - pip freeze
before_script:
  - "[ $NUMPY = latest ] && pip install --upgrade numpy || pip install numpy==$NUMPY"
  - "[ $PANDAS = latest ] && pip install --upgrade pandas || pip install pandas==$PANDAS"
  - "[ $SCIKITLEARN = latest ] && pip install --upgrade scikit-learn || pip install scikit-learn==$SCIKITLEARN"
  - "[ $DASK = latest ] && pip install --upgrade dask || pip install dask==$DASK"
  - "[ $DISTRIBUTED = latest ] && pip install --upgrade distributed || pip install distributed==$DISTRIBUTED"
  # need to downgrade tornado manually
  - "[ $SCIPY = latest ] || pip install tornado==4.5.3"
  - "[ $SCIPY = latest ] && pip install --upgrade scipy || pip install scipy==$SCIPY"
  - pip list
  - sed -i -e 's/-n auto/-n 2/g' setup.cfg
  - sed -e '/^\s*--cov tsfresh/d' setup.cfg > setup-nocov.cfg
env:
  global:
    - PYTEST_ADDOPTS="-c setup-nocov.cfg"
jobs:
  # some dependencies are not yet ready for Python 3.8
  allow_failures:
    - python: 3.8
  fast_finish: true
  include:
    - stage: Run tests
      env: NUMPY="latest", PANDAS="latest", SCIKITLEARN="latest", DASK="latest", DISTRIBUTED="latest", SCIPY="latest"
      python: 3.8
      script: &test
        - "if [ $TRAVIS_PULL_REQUEST = false ] && ! [ $TRAVIS_BRANCH = master ]; then pytest tests/units; else pytest tests; fi"
    - env: NUMPY="latest", PANDAS="latest", SCIKITLEARN="latest", DASK="latest", DISTRIBUTED="latest", SCIPY="latest" PYTEST_ADDOPTS="-c setup.cfg"
      python: 3.7
      script: *test
    - env: NUMPY="latest", PANDAS="latest", SCIKITLEARN="latest", DASK="latest", DISTRIBUTED="latest", SCIPY="latest"
      python: 3.6
      script: *test
    - env: NUMPY="latest", PANDAS="latest", SCIKITLEARN="latest", DASK="latest", DISTRIBUTED="latest", SCIPY="latest"
      # pandas 0.25 requires python >= 3.5.3
      python: 3.5.3
      script: *test
    - env: NUMPY="1.15.1", PANDAS="0.23.2", SCIKITLEARN="0.19.2", DASK="0.16.1", DISTRIBUTED="1.18.3", SCIPY="1.2.0"
      python: 3.7
      script: *test
    - env: NUMPY="1.12.0", PANDAS="0.20.3", SCIKITLEARN="0.19.0", DASK="0.15.2", DISTRIBUTED="1.18.3", SCIPY="1.2.0"
      python: 3.6
      script: *test
    - env: NUMPY="1.12.0", PANDAS="0.20.3", SCIKITLEARN="0.19.0", DASK="0.15.2", DISTRIBUTED="1.18.3", SCIPY="1.2.0"
      python: 3.5.3
      script: *test

    - stage: Test coverage
      if: env(PYTEST_ADDOPTS) = "-c setup.cfg" AND fork = false
      script: coveralls

    - stage: Deploy
      if: tag IS present AND fork = false
      python: 3.7
      deploy:
        provider: pypi
        user: MaxChrist
        password:
          secure: Jh0Z69Mh+esOpegXyXoecFOkpMhaQaiJbQVEvVvQ2K1rCmCE20a19/TGfPUrynpqOYXZvvb5Ok6CtlzAi9J5huA3MRSf4iYPsUe8i7n0FK4JU5BP7VqM3/7cQZMdD5SeYFV3e3JURDcKYfoG7N+DNb+LfluYK5MBkRLhdEVRqSeHocPY4QRzzhJi1ljX99ThdRPrsQqYaD3tpZxJhbJDgHLtvMr39+407uQSDnubvFz3iu90DZiN2fIP5bEN6PDuaGXNZMA1p40DjSkGc7epg0U4vHn6CSya1nXlqjXUqXYJY5Ha2kbMAN7hfmU+gId09+FSHQRuanKJkRqSBksVgATCAeSAiqAe3EPAsG75ewhXDeusQZMzRy7DxQzjOJG9oIyWMVmZFlIoNlpg2eifN9uUc7FfyGHiVfWwUDslszpc/81hQViMPP0NoMAop4zcWR3ChCMnHMycPQEmWuV65WfL7yN6SuTokxSmepubPtFs+4UIlI0rgZWCHVIgGZqI8LFn958pLtpQ+32Ew8HGU3IiOfao9HbGreQ2Lgqo2L2EyNDWiHfJ3oZ1+6BP/1GqI6j7x7oPdwoE1jvY4CSC7iMAiieZNnrvywvmJpZB69CGefxQJzWcm+yD03QwNBFFaabCbKwbn+q3eUOUrPRuvTkhVLRWDxQNH/zaZyuZQ+Q=
        distributions: "sdist bdist_wheel"
        on:
          tags: true
          repo: blue-yonder/tsfresh
notifications:
   slack: tsfresh:uIzPVnlBQs32xE5jbq34f0Cq
